# These are supported funding model platforms

custom: # Replace with up to 4 custom sponsorship URLs
  - https://paypal.me/MLomadilla
  - https://buymeacoffee.com/cruelninja
  - https://your-custom-donation-link.com
